import React from 'react';

import GeneratedIcon from './GeneratedIcon';

import { icon } from '../../components/Marker/icons';
const icons = [ 'EVENT_ART', 'EVENT_COMEDY', 'EVENT_CRAFTS', 'EVENT_FILM', 'EVENT_FOOD', 'EVENT_MUSIC', 'EVENT_THEATER' ];

class AutoGeneratedIcons extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      markers: []
    };
  }
  componentDidMount() {
    this.intervalId = setInterval(() => {
      const randomTop = Math.floor(Math.random() * 100) + 1;
      const randomLeft = Math.floor(Math.random() * 100) + 1;
      const randomIcon = Math.floor(Math.random() * icons.length) + 0;

      this.setState({
        markers: [
          ...this.state.markers,
          {
            icon: icon[icons[randomIcon]],
            top: randomTop,
            left: randomLeft
          }
        ]
      });

      if(this.state.markers.length > 3) {
        this.state.markers.shift();
      }
    }, 3000);
  }
  componentWillUnmount() {
    clearInterval(this.intervalId);
  }
  render() {
    return(
      this.state.markers.map((marker, i) => (
        <GeneratedIcon
          key={i}
          src={marker.icon}
          top={marker.top}
          left={marker.left}
        />
      ))
    );
  }
}

export default AutoGeneratedIcons;
