import React from 'react';
import FacebookLogin from 'react-facebook-login/dist/facebook-login-render-props';

import AutoGeneratedIcons from './AutoGeneratedIcons';
import LandingWrapper from './LandingWrapper';
import map from './map.jpeg';

import { H2, FacebookButton } from '../../../styled-components';

const Landing = ({ facebookLogin }) => (
  <LandingWrapper bg={map} center fullscreen>
    <H2 style={{fontSize: '90px'}}>GATR</H2>
    <H2>Know what’s happening all around you</H2>
    <h3 style={{color: 'white'}}>Find out all shows, events, movies, sports and more around your city or schedule your own party and invite your friends</h3>
    <FacebookLogin
      appId="140423843185571"
      callback={facebookLogin}
      render={renderProps => <FacebookButton onClick={renderProps.onClick}>Login with Facebook</FacebookButton>}
    />
    <AutoGeneratedIcons />
  </LandingWrapper>
);

export default Landing;
